### PR TITLE
Fix logging configuration for CLI

### LINKED ISSUE #703: Resolve StanfordNLP logging hotfix
#701 suppresses the logging of StanfordNLP programmatically. This is a hotfix and should be done properly via an SLF4J configuration in the future.

### PR DESCRIPTION
**Pull request by dfuchss**
Resolves #703

### CODE REVIEW

File: cli/src/main/java/de/jplag/cli/logger/CollectedLogger.java [hunk 1]
```diff
@@ -117,7 +122,11 @@ private String computeShortName() {
     }
 
     private boolean isLevelEnabled(int logLevel) {
-        return logLevel >= CURRENT_LOG_LEVEL;
+        return isJPlagLog() ? logLevel >= CURRENT_LOG_LEVEL : logLevel >= LOG_LEVEL_FOR_EXTERNAL_LIBRARIES;
```
Comment (JanWittler) [inline cli/src/main/java/de/jplag/cli/logger/CollectedLogger.java:125]:
```suggestion
        return logLevel >= (isJPlagLog() ? CURRENT_LOG_LEVEL : LOG_LEVEL_FOR_EXTERNAL_LIBRARIES);
```

**Review by JanWittler — APPROVED** [review]
